### ISSUE TITLE
Implement details of "canonical" Miden ABI

### ISSUE THREAD

**Issue by bitwalker** [0xMiden/compiler#122]
Currently, we have an informally specified canonical ABI (hereafter referred to as the "Miden ABI") that the compiler uses for generating code when compiling to Miden Assembly. We need to expand on this in the following ways:

```[tasklist]
### Tasks
- [ ] Specify the conditions and procedure for spilling arguments to the advice provider
- [ ] Provide a specification document covering the details of the Miden ABI
- [ ] Identify any changes necessary to maximize compatibility with the Wasm Component Model's "Canonical ABI"
- [ ] Implement any necessary changes in the compiler to ensure we are supporting the Canonical ABI on top of the Miden ABI correctly
```

It is possible that we'll need separate ABI variants for kernel procedures (i.e. `syscall` targets), as well as procedures which can be the target of an indirect call (e.g. via `dynexec`), but for now we'll try to unify these under a single ABI.

**Comment by bitwalker** [comment]
Closing this as effectively completed, in that the various ABI and calling convention details are now documented. We have other issues open that deal with specific edge cases that are not fully implemented yet
